(() => {
'use strict';
const C={storageKey:'azaman-sat-practice-v2',accessCodes:['SAT26','PRACTICE','AZM-SAT'],roomCode:'AZM24',startCode:'492776',breakSeconds:600,fiveMinuteWarning:300,modules:[
{id:'rw1',section:'Reading and Writing',label:'Module 1',minutes:32,count:27,kind:'rw1'},
{id:'rw2',section:'Reading and Writing',label:'Module 2',minutes:32,count:27,kind:'rw2'},
{id:'math1',section:'Math',label:'Module 1',minutes:35,count:22,kind:'math1'},
{id:'math2',section:'Math',label:'Module 2',minutes:35,count:22,kind:'math2'}],letters:['A','B','C','D']};
const app=document.getElementById('app');const BANK=window.SAT_QUESTIONS||{};let state=load()||fresh(),timer=null,brk=null;
function fresh(){return{version:2,screen:'access',student:'',accessCode:'',roomCode:'',startCode:'',currentModuleIndex:0,currentQuestion:0,moduleStartedAt:null,breakStartedAt:null,remainingSec:null,answers:{},marked:{},eliminated:{},notes:{},highlights:{},completedModules:{},submitted:false,testStarted:false,warningShown:{},adaptive:{rw:null,math:null},_timerHidden:false,_lineReader:false,_rulesAccepted:false,_deskReady:false};}
function load(){try{const v=JSON.parse(localStorage.getItem(C.storageKey));return v&&v.version===2?v:null;}catch(_){return null;}}
function save(){try{localStorage.setItem(C.storageKey,JSON.stringify(state));}catch(_){}}
function reset(){stop();try{localStorage.removeItem(C.storageKey);}catch(_){}state=fresh();render();}
function stop(){if(timer)clearInterval(timer);if(brk)clearInterval(brk);timer=brk=null;}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function mod(){return C.modules[state.currentModuleIndex];}
function qs(index=state.currentModuleIndex){const m=C.modules[index];if(m.kind==='rw2')return BANK.rw2?.[state.adaptive.rw||'easy']||[];if(m.kind==='math2')return BANK.math2?.[state.adaptive.math||'easy']||[];return BANK[m.kind]||[];}
function q(){return qs()[state.currentQuestion]||{prompt:'Question content is not loaded.',options:['A','B','C','D'],answer:'A',domain:'Unknown',skill:'Unknown',difficulty:'medium'};}
function key(i=state.currentQuestion){return `${mod().id}-${i}`;}
function answered(i=state.currentQuestion){const v=state.answers[key(i)];return v!==undefined&&v!=='';}
function marked(i=state.currentQuestion){return!!state.marked[key(i)];}
function fmt(s){s=Math.max(0,Math.floor(s));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function remaining(){return state.moduleStartedAt?Math.max(0,(state.remainingSec??mod().minutes*60)-Math.floor((Date.now()-state.moduleStartedAt)/1000)):state.remainingSec??mod().minutes*60;}
function show(screen){state.screen=screen;save();render();}
function render(){stop();if(state.screen==='test'&&state.moduleStartedAt)startTimer();if(state.screen==='break'&&state.breakStartedAt)startBreak();app.innerHTML=html();bind();}
function startTimer(){timer=setInterval(()=>{if(state.screen!=='test')return;const s=remaining();state.remainingSec=s;save();const n=document.getElementById('timer');if(n){n.textContent=fmt(s);n.classList.toggle('warning',s<=C.fiveMinuteWarning);n.classList.toggle('hidden',state._timerHidden&&s>C.fiveMinuteWarning);}if(s===C.fiveMinuteWarning&&!state.warningShown[mod().id]){state.warningShown[mod().id]=true;save();warning();}if(s<=0)completeModule();},250);}
function startBreak(){brk=setInterval(()=>{const s=Math.max(0,C.breakSeconds-Math.floor((Date.now()-(state.breakStartedAt||Date.now()))/1000));const n=document.getElementById('breakClock');if(n)n.textContent=fmt(s);if(s<=0){stop();state.breakStartedAt=null;state.currentModuleIndex=2;state.currentQuestion=0;state.screen='directions';save();render();}},250);}
function startModule(){if(state.completedModules[mod().id])return;state.testStarted=true;state.moduleStartedAt=Date.now();state.remainingSec=mod().minutes*60;state.currentQuestion=0;state._timerHidden=false;state._lineReader=false;save();show('test');}
function chooseAdaptive(kind,id){const bank=BANK[id]||[];let good=0;bank.forEach((x,i)=>{const v=state.answers[`${id}-${i}`];if(v!==undefined&&String(v).trim().toLowerCase()===String(x.answer).trim().toLowerCase())good++;});state.adaptive[kind]=bank.length&&good/bank.length>=.7?'hard':'easy';save();}
function completeModule(){stop();state.remainingSec=0;state.completedModules[mod().id]=true;if(mod().id==='rw1')chooseAdaptive('rw','rw1');if(mod().id==='math1')chooseAdaptive('math','math1');if(mod().id==='rw2'){state.currentModuleIndex=2;state.currentQuestion=0;state.remainingSec=null;state.moduleStartedAt=null;state.breakStartedAt=Date.now();state.screen='break';save();render();return;}if(mod().id==='math2'){state.submitted=true;state.testStarted=false;state.moduleStartedAt=null;state.screen='finish';save();render();return;}state.currentModuleIndex++;state.currentQuestion=0;state.remainingSec=null;state.moduleStartedAt=null;state.screen='directions';save();render();}
function answer(v){state.answers[key()]=v;save();render();focusQuestion();}
function spr(v){state.answers[key()]=v.trim();save();}
function toggleMark(){const k=key();state.marked[k]=!state.marked[k];save();render();focusQuestion();}
function eliminate(i){const k=key(),set=new Set(state.eliminated[k]||[]);set.has(i)?set.delete(i):set.add(i);state.eliminated[k]=[...set];save();render();focusQuestion();}
function note(){const k=key(),v=prompt('Add a note for this question:',state.notes[k]||'');if(v===null)return;state.notes[k]=v.trim();save();toast(v.trim()?'Note saved':'Note removed');}
function highlight(){const s=getSelection(),t=s?.toString().trim();if(!t||!s.rangeCount)return toast('Select text in the source panel first.');const k=key(),a=state.highlights[k]||[];if(!a.includes(t))a.push(t);state.highlights[k]=a.slice(-12);s.removeAllRanges();save();toast('Highlight saved');render();}
function toast(t){let n=document.getElementById('toast');if(!n){n=document.createElement('div');n.id='toast';n.className='toast';document.body.appendChild(n);}n.textContent=t;n.classList.add('show');clearTimeout(n._h);n._h=setTimeout(()=>n.classList.remove('show'),1800);}
function go(i){if(i<0||i>=qs().length||state.completedModules[mod().id])return;state.currentQuestion=i;save();closeOverlays();render();focusQuestion();}
function next(){state.currentQuestion<qs().length-1?(state.currentQuestion++,save(),render(),focusQuestion()):review();}
function back(){if(state.currentQuestion>0){state.currentQuestion--;save();render();focusQuestion();}}
function focusQuestion(){setTimeout(()=>document.getElementById('questionPrompt')?.focus(),0);}
function warning(){closeOverlays();const n=document.createElement('div');n.className='modal-backdrop';n.innerHTML='<div class="modal warning-modal" role="dialog" aria-modal="true" aria-labelledby="warnTitle"><h3 id="warnTitle">5 minutes remaining</h3><p>Five minutes remain in this module. The timer must remain visible until the module ends.</p><div class="modal-actions"><button class="btn" id="dismissWarn">Continue</button></div></div>';document.body.appendChild(n);n.querySelector('#dismissWarn').focus();n.querySelector('#dismissWarn').onclick=()=>n.remove();}
function review(){closeOverlays();const m=mod(),a=qs(),un=a.filter((_,i)=>!answered(i)).length,fl=a.filter((_,i)=>marked(i)).length,n=document.createElement('div');n.id='reviewModal';n.className='modal-backdrop';n.innerHTML=`<div class="modal review-modal" role="dialog" aria-modal="true" aria-labelledby="reviewTitle"><div class="modal-head"><h3 id="reviewTitle">Review questions</h3><button class="icon-btn" id="closeReview" aria-label="Close">×</button></div><p class="small">Answered: ${a.length-un} · Unanswered: ${un} · Marked: ${fl}</p><div class="review-grid">${a.map((_,i)=>`<button class="review-q ${answered(i)?'answered':''} ${marked(i)?'marked':''}" data-q="${i}" aria-label="Question ${i+1}${answered(i)?', answered':''}${marked(i)?', marked for review':''}">${i+1}</button>`).join('')}</div><div class="modal-actions"><button class="btn" id="closeReview2">Back to question</button><button class="btn primary-action" id="submitModule">Finish module</button></div></div>`;document.body.appendChild(n);n.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{n.remove();go(+b.dataset.q);});n.querySelector('#closeReview').onclick=()=>n.remove();n.querySelector('#closeReview2').onclick=()=>n.remove();n.querySelector('#submitModule').onclick=()=>{n.remove();completeModule();};}
function openTools(){closeTools();const n=document.createElement('div');n.id='toolPopover';n.className='tool-popover';const canHide=remaining()>C.fiveMinuteWarning;let h=`<div class="tool-head"><b>Test tools</b><button id="closeTools" class="icon-btn" aria-label="Close tools">×</button></div><button class="tool-item" id="noteTool">Note</button>${mod().section==='Reading and Writing'?'<button class="tool-item" id="hlTool">Highlight selection</button>':''}<button class="tool-item" id="lineTool">${state._lineReader?'Turn off line reader':'Line reader'}</button><button class="tool-item" id="timerTool">${state._timerHidden&&canHide?'Show timer':'Hide timer'}</button>${mod().section==='Math'?'<button class="tool-item" id="calcTool">Calculator</button><button class="tool-item" id="refTool">Reference sheet</button>':''}<button class="tool-item" id="zoomOut">Zoom out</button><button class="tool-item" id="zoomIn">Zoom in</button>`;n.innerHTML=h;document.body.appendChild(n);n.querySelector('#closeTools').onclick=closeTools;n.querySelector('#noteTool').onclick=()=>{closeTools();note();};n.querySelector('#hlTool')?.addEventListener('click',()=>{closeTools();highlight();});n.querySelector('#lineTool').onclick=()=>{state._lineReader=!state._lineReader;save();closeTools();render();};n.querySelector('#timerTool').onclick=()=>{if(!canHide){state._timerHidden=false;toast('The timer cannot be hidden with 5 minutes remaining.');}else state._timerHidden=!state._timerHidden;save();closeTools();render();};n.querySelector('#calcTool')?.addEventListener('click',()=>{closeTools();calculator();});n.querySelector('#refTool')?.addEventListener('click',()=>{closeTools();reference();});n.querySelector('#zoomOut').onclick=()=>zoom(-.05);n.querySelector('#zoomIn').onclick=()=>zoom(.05);}
function closeTools(){document.getElementById('toolPopover')?.remove();}
function closeOverlays(){closeTools();['calculatorPanel','referencePanel','reviewModal'].forEach(id=>document.getElementById(id)?.remove());}
function zoom(delta){const cur=Number(getComputedStyle(document.documentElement).getPropertyValue('--zoom-scale')||1);document.documentElement.style.setProperty('--zoom-scale',Math.min(1.25,Math.max(.85,cur+delta)));}
function calculator(){closeOverlays();const n=document.createElement('div');n.id='calculatorPanel';n.className='overlay-panel';n.innerHTML='<div class="panel-head"><b>Calculator</b><button class="icon-btn" id="closeCalc" aria-label="Close calculator">×</button></div><input id="calcDisplay" class="calc-display mono" readonly aria-label="Calculator display"><div class="calc-grid">'+['7','8','9','÷','4','5','6','×','1','2','3','−','0','.','(',')','+','⌫','=','C'].map(v=>`<button class="calc-key" data-calc="${v}">${v}</button>`).join('')+'</div>';document.body.appendChild(n);let exp='';const d=n.querySelector('#calcDisplay');n.querySelector('#closeCalc').onclick=()=>n.remove();n.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>{const v=b.dataset.calc;if(v==='C')exp='';else if(v==='⌫')exp=exp.slice(0,-1);else if(v==='='){try{exp=String(evalMath(exp));}catch(_){exp='Error';}}else exp=exp==='Error'?v:exp+v;d.value=exp;});}
function evalMath(e){const x=e.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-');if(!x||!/^[0-9+*/(). -]+$/.test(x))throw Error();const t=x.match(/\d+(?:\.\d+)?|[()+\-*/]/g)||[],o=[],s=[],p={'+':1,'-':1,'*':2,'/':2};t.forEach(v=>{if(/^\d/.test(v))o.push(+v);else if(v==='(')s.push(v);else if(v===')'){while(s.length&&s.at(-1)!=='(')o.push(s.pop());if(s.pop()!=='(')throw Error();}else{while(s.length&&s.at(-1)!=='('&&p[s.at(-1)]>=p[v])o.push(s.pop());s.push(v);}});while(s.length){if(s.at(-1)==='(')throw Error();o.push(s.pop());}t.length=0;for(const v of o)if(typeof v==='number')t.push(v);else{const b=t.pop(),a=t.pop();if(a===undefined||b===undefined)throw Error();t.push({'+':a+b,'-':a-b,'*':a*b,'/':a/b}[v]);}if(t.length!==1||!Number.isFinite(t[0]))throw Error();return t[0];}
function reference(){closeOverlays();const n=document.createElement('div');n.id='referencePanel';n.className='overlay-panel reference-panel';n.innerHTML='<div class="panel-head"><b>Reference sheet</b><button class="icon-btn" id="closeRef" aria-label="Close reference sheet">×</button></div><h4>Common formulas</h4><p><b>Circle:</b> C = 2πr, A = πr²</p><p><b>Triangle:</b> A = ½bh</p><p><b>Rectangle:</b> A = lw</p><p><b>Rectangular prism:</b> V = lwh</p><p><b>Cylinder:</b> V = πr²h</p><p><b>Pythagorean theorem:</b> a² + b² = c²</p><p><b>Slope:</b> m = (y₂ − y₁)/(x₂ − x₁)</p><p><b>Distance:</b> d = √((x₂ − x₁)² + (y₂ − y₁)²)</p><p><b>Percent:</b> new = original × (1 ± rate)</p><p><b>Right triangle:</b> sin θ = opp/hyp, cos θ = adj/hyp, tan θ = opp/adj</p>';document.body.appendChild(n);n.querySelector('#closeRef').onclick=()=>n.remove();}
function table(t){return`<div class="data-table"><table><thead><tr>${t.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function source(x){let h=`<div class="source-label">${esc(x.domain||'Source')}</div>`;if(x.source?.title)h+=`<div class="source-title">${esc(x.source.title)}</div>`;if(x.source?.paragraphs?.length)h+=`<div class="passage">${x.source.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</div>`;else if(x.source?.table)h+=table(x.source.table);else if(x.source?.quote)h+=`<blockquote class="quoted">${esc(x.source.quote)}</blockquote>`;else h+='<div class="passage"><p>Use the information in the question to determine the best answer.</p></div>';const hs=state.highlights[key()]||[];if(hs.length)h+=`<div class="annotation-list"><b>Saved highlights</b>${hs.map(v=>`<span>“${esc(v)}”</span>`).join('')}</div>`;if(state.notes[key()])h+=`<div class="annotation-note"><b>Note:</b> ${esc(state.notes[key()])}</div>`;return h;}
function choices(x){const v=state.answers[key()]??'',e=new Set(state.eliminated[key()]||[]);return`<div class="choices" role="radiogroup" aria-label="Answer choices">${x.options.map((o,i)=>`<div class="choice-wrap ${e.has(i)?'eliminated':''}"><button class="choice ${v===C.letters[i]?'selected':''}" data-answer="${C.letters[i]}" aria-pressed="${v===C.letters[i]}"><span class="choice-letter">${C.letters[i]}</span><span>${esc(o)}</span></button><button class="eliminate-btn" data-eliminate="${i}" aria-label="${e.has(i)?'Restore':'Cross out'} option ${C.letters[i]}">${e.has(i)?'Restore':'Cross out'}</button></div>`).join('')}</div>`;}
function sprHtml(){return`<div class="spr-wrap"><label for="spr">Enter your answer</label><input id="spr" class="spr-input mono" inputmode="decimal" autocomplete="off" value="${esc(state.answers[key()]??'')}" placeholder="Answer"><p class="small">Enter a non-negative integer, decimal, or fraction.</p></div>`;}
function shell(inner){return`<div class="app-shell"><header class="topbar"><div class="brand"><div class="brand-mark">AZ</div><div class="brand-name">Azaman SAT Practice</div></div><div class="topbar-right">${state.student?`<span class="topbar-student">${esc(state.student)}</span>`:''}</div></header>${inner}</div>`;}
function access(){return`<main class="page"><section class="card compact"><div class="kicker">Practice exam</div><h1>Sign in</h1><p>Use the practice access code supplied for this session.</p><div class="field"><label for="access">Access code</label><input id="access" class="text-input center mono" maxlength="12" autocomplete="off" value="${esc(state.accessCode)}" placeholder="SAT26"></div><div class="field"><label for="student">Name shown during testing</label><input id="student" class="text-input" maxlength="60" value="${esc(state.student)}" placeholder="Your name"></div><div class="btn-row"><button id="accessBtn" class="btn wide">Continue</button></div><p class="small">Demo codes: <b>SAT26</b>, <b>PRACTICE</b>, <b>AZM-SAT</b></p><div class="divider"></div><button id="resetBtn" class="btn link small">Reset local test state</button></section></main>`;}
function checkin(){return`<main class="page"><section class="card"><div class="kicker">Test-day setup</div><h2>Before you test</h2><p>This practice simulator uses the digital SAT two-section, four-module structure.</p><div class="info-grid"><div class="info-box"><div class="value">98</div><div class="label">Questions</div></div><div class="info-box"><div class="value">134</div><div class="label">Testing minutes</div></div><div class="info-box"><div class="value">10:00</div><div class="label">Break</div></div><div class="info-box"><div class="value">4</div><div class="label">Modules</div></div></div><ul class="check-list"><li>Keep your workspace clear.</li><li>Move between questions only within the active module.</li><li>Answers save automatically in this browser.</li><li>When a module ends, it is locked.</li></ul><label class="ack"><input id="rulesAck" type="checkbox" ${state._rulesAccepted?'checked':''}> <span>I have read the practice test reminders.</span></label><label class="ack"><input id="deskAck" type="checkbox" ${state._deskReady?'checked':''}> <span>I have cleared my workspace.</span></label><div class="btn-row"><button id="checkinBtn" class="btn" ${state._rulesAccepted&&state._deskReady?'':'disabled'}>Continue</button></div></section></main>`;}
function room(){return`<main class="page"><section class="card compact"><div class="kicker">Check-in</div><h2>Enter room code</h2><p>Your proctor provides the room code.</p><div class="field"><label for="room">Room code</label><input id="room" class="text-input center mono" maxlength="5" autocomplete="off" value="${esc(state.roomCode)}" placeholder="AZM24"></div><div class="btn-row"><button id="roomBtn" class="btn">Next</button></div></section></main>`;}
function startCode(){return`<main class="page"><section class="card compact center-card"><div class="kicker">Ready to begin</div><h2>Enter start code</h2><p>Your proctor announces the start code when the room is ready.</p><div class="code-row">${Array.from({length:6},(_,i)=>`<input class="code-input start-digit" maxlength="1" inputmode="numeric" data-pos="${i}" aria-label="Start code digit ${i+1}" value="${esc(state.startCode[i]||'')}">`).join('')}</div><div class="btn-row center-row"><button id="startTestBtn" class="btn">Start test</button></div></section></main>`;}
function directions(){const m=mod(),isMath=m.section==='Math',v=m.id==='rw2'?state.adaptive.rw:m.id==='math2'?state.adaptive.math:null;return`<main class="page"><section class="card"><div class="kicker">${esc(m.section)} · ${esc(m.label)}</div><h2>Directions</h2><p>${isMath?'Calculator use is permitted on every Math question. A calculator and reference sheet are available through Test tools.':'Each question uses a short passage or set of information. Choose the answer that best completes the task.'}</p><div class="info-grid"><div class="info-box"><div class="value">${m.minutes}:00</div><div class="label">Module time</div></div><div class="info-box"><div class="value">${m.count}</div><div class="label">Questions</div></div></div>${v?`<div class="notice">Practice routing selected the <b>${esc(v)}</b> difficulty variant for this module.</div>`:''}<ul class="check-list"><li>The timer runs for this module only.</li><li>You can use the question menu before submitting.</li><li>After submission, this module cannot be reopened.</li></ul><div class="btn-row"><button id="beginModuleBtn" class="btn">Begin module</button></div></section></main>`;}
function test(){const m=mod(),x=q(),s=remaining(),hide=state._timerHidden&&s>C.fiveMinuteWarning;return`<div class="test-shell"><header class="test-top"><div class="test-title">${esc(m.section)} · ${esc(m.label)}</div><div class="test-counter">Question ${state.currentQuestion+1} of ${m.count}</div><div id="timer" class="timer ${s<=C.fiveMinuteWarning?'warning':''} ${hide?'hidden':''}" aria-live="polite">${fmt(s)}</div><button id="toolsBtn" class="nav-pill">Test tools</button></header><main class="test-main"><section class="source-panel" id="sourcePanel">${source(x)}</section><section class="question-panel"><div class="question-card"><div class="q-meta">${esc(x.domain||'Question')} · ${esc(x.skill||'')} · ${esc(x.difficulty||'')}</div><h2 class="q-prompt" id="questionPrompt" tabindex="-1">${esc(x.prompt)}</h2>${x.type==='spr'?sprHtml():choices(x)}</div></section></main><footer class="test-footer"><div class="footer-left"><button id="markBtn" class="nav-pill">${marked()?'Unmark':'Mark for review'}</button><button id="reviewBtn" class="nav-pill">Question menu</button>${state.notes[key()]?'<span class="annotation-chip">Note saved</span>':''}</div><div class="footer-center"><button id="prevBtn" class="nav-pill" ${state.currentQuestion===0?'disabled':''}>Back</button><button id="nextBtn" class="nav-pill primary">${state.currentQuestion===m.count-1?'Review module':'Next'}</button></div><div class="footer-right"><span class="small">${esc(m.section)}</span></div></footer>${state._lineReader?'<div class="line-reader" aria-hidden="true"></div>':''}</div>`;}
function breakScreen(){const s=Math.max(0,C.breakSeconds-Math.floor((Date.now()-(state.breakStartedAt||Date.now()))/1000));return`<main class="page"><section class="card compact center-card"><div class="kicker">Section break</div><h1>10-minute break</h1><p>Reading and Writing is complete. The break is required before Math begins.</p><div id="breakClock" class="break-clock">${fmt(s)}</div><p class="small">You cannot advance early from this practice simulation.</p></section></main>`;}
function finish(){const sc=score();return`<main class="page"><section class="card compact center-card"><div class="kicker">Practice complete</div><h1>Test submitted</h1><p>All responses are saved locally. This simulator does not submit results to College Board.</p><div class="info-grid"><div class="info-box"><div class="value">${sc.correct}</div><div class="label">Correct</div></div><div class="info-box"><div class="value">${sc.answered}</div><div class="label">Answered</div></div><div class="info-box"><div class="value">98</div><div class="label">Questions</div></div><div class="info-box"><div class="value">${sc.percent}%</div><div class="label">Accuracy</div></div></div><div class="btn-row center-row"><button id="restartBtn" class="btn">Start another practice test</button></div></section></main>`;}
function score(){let correct=0,answeredCount=0,total=0;C.modules.forEach((m,i)=>{const a=qs(i);total+=a.length;a.forEach((x,j)=>{const v=state.answers[`${m.id}-${j}`];if(v!==undefined&&String(v).trim()!==''){answeredCount++;if(String(v).trim().toLowerCase()===String(x.answer).trim().toLowerCase())correct++;}});});return{correct,answered:answeredCount,percent:total?Math.round(correct/total*100):0};}
function html(){switch(state.screen){case'access':return shell(access());case'checkin':return shell(checkin());case'room':return shell(room());case'startcode':return shell(startCode());case'directions':return shell(directions());case'test':return test();case'break':return shell(breakScreen());case'finish':return shell(finish());default:return shell(access());}}
function bind(){if(state.screen==='access'){document.getElementById('access')?.addEventListener('input',e=>{state.accessCode=e.target.value.toUpperCase();save();});document.getElementById('student')?.addEventListener('input',e=>{state.student=e.target.value;save();});document.getElementById('accessBtn')?.addEventListener('click',()=>{if(!C.accessCodes.includes(state.accessCode.trim().toUpperCase()))return toast('Invalid practice access code.');if(!state.student.trim())return toast('Enter a name.');show('checkin');});document.getElementById('resetBtn')?.addEventListener('click',reset);}
if(state.screen==='checkin'){document.getElementById('rulesAck')?.addEventListener('change',e=>{state._rulesAccepted=e.target.checked;save();render();});document.getElementById('deskAck')?.addEventListener('change',e=>{state._deskReady=e.target.checked;save();render();});document.getElementById('checkinBtn')?.addEventListener('click',()=>{if(state._rulesAccepted&&state._deskReady)show('room');});}
if(state.screen==='room'){document.getElementById('room')?.addEventListener('input',e=>{state.roomCode=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,5);e.target.value=state.roomCode;save();});document.getElementById('roomBtn')?.addEventListener('click',()=>{if(state.roomCode!==C.roomCode)return toast('Invalid room code.');state.startCode='';show('startcode');document.querySelector('.start-digit')?.focus();});}
if(state.screen==='startcode'){const d=[...document.querySelectorAll('.start-digit')];d.forEach((n,i)=>n.addEventListener('input',e=>{n.value=e.target.value.replace(/\D/g,'').slice(-1);state.startCode=d.map(x=>x.value).join('');save();if(n.value&&d[i+1])d[i+1].focus();}));document.getElementById('startTestBtn')?.addEventListener('click',()=>{if(state.startCode!==C.startCode)return toast('Invalid start code.');state.currentModuleIndex=0;state.currentQuestion=0;state.screen='directions';save();render();});}
if(state.screen==='directions')document.getElementById('beginModuleBtn')?.addEventListener('click',startModule);
if(state.screen==='test'){document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answer(b.dataset.answer)));document.querySelectorAll('[data-eliminate]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();eliminate(+b.dataset.eliminate);}));document.getElementById('spr')?.addEventListener('input',e=>spr(e.target.value));document.getElementById('markBtn')?.addEventListener('click',toggleMark);document.getElementById('reviewBtn')?.addEventListener('click',review);document.getElementById('prevBtn')?.addEventListener('click',back);document.getElementById('nextBtn')?.addEventListener('click',next);document.getElementById('toolsBtn')?.addEventListener('click',openTools);}
if(state.screen==='finish')document.getElementById('restartBtn')?.addEventListener('click',reset);}
document.addEventListener('keydown',e=>{if(state.screen!=='test'||['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.key.toLowerCase()==='f'){toggleMark();e.preventDefault();}else if(e.key.toLowerCase()==='m'){review();e.preventDefault();}else if(e.key.toLowerCase()==='t'){openTools();e.preventDefault();}else if(e.key==='ArrowRight'){next();e.preventDefault();}else if(e.key==='ArrowLeft'){back();e.preventDefault();}else if(e.key==='Escape'){closeOverlays();}},false);
window.resetAzamanSAT=reset;render();
})();
