(()=>{"use strict";
const C={storageKey:"azaman-sat-practice-v3",accessCodes:["SAT26","PRACTICE","AZM-SAT"],roomCode:"AZM24",startCode:"492776",breakSec:600,warnSec:300,mods:[
{id:"rw1",section:"Reading and Writing",label:"Module 1",minutes:32,count:27,bank:"rw1"},{id:"rw2",section:"Reading and Writing",label:"Module 2",minutes:32,count:27,bank:"rw2"},{id:"math1",section:"Math",label:"Module 1",minutes:35,count:22,bank:"math1"},{id:"math2",section:"Math",label:"Module 2",minutes:35,count:22,bank:"math2"}],letters:["A","B","C","D"]};
const A=document.getElementById("app"),B=window.SAT_QUESTIONS||{};let s=load()||fresh(),tick=null;
function fresh(){return{v:3,screen:"access",student:"",email:"",password:"",accessCode:"",roomCode:"",startCode:"",step:1,infoOk:false,aids:{},pledge:"",roomOk:false,mi:0,qi:0,endAt:null,breakEndAt:null,answers:{},marked:{},eliminated:{},notes:{},highlights:{},completed:{},submitted:false,adaptive:{rw:"easy",math:"easy"},timerHidden:false,lineReader:false,rules:false,desk:false,warning:{}}}
function load(){try{const x=JSON.parse(localStorage.getItem(C.storageKey));return x?.v===3?x:null}catch(_){return null}}
function save(){try{localStorage.setItem(C.storageKey,JSON.stringify(s))}catch(_){} }
function stop(){if(tick)clearInterval(tick);tick=null}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function m(){return C.mods[s.mi]}
function bank(){const x=m();return x.id==="rw2"?B.rw2?.[s.adaptive.rw]||[]:x.id==="math2"?B.math2?.[s.adaptive.math]||[]:B[x.bank]||[]}
function q(){return bank()[s.qi]||{prompt:"Question unavailable",options:["A","B","C","D"],answer:"A",domain:"Unknown",skill:"Unknown",difficulty:"medium"}}
function qkey(i=s.qi){return`${m().id}-${i}`}
function answered(i=s.qi){return s.answers[qkey(i)]!==undefined&&s.answers[qkey(i)]!==""}
function marked(i=s.qi){return!!s.marked[qkey(i)]}
function fmt(x){x=Math.max(0,Math.floor(x));return`${String(Math.floor(x/60)).padStart(2,"0")}:${String(x%60).padStart(2,"0")}`}
function rem(){return s.endAt?Math.max(0,Math.ceil((s.endAt-Date.now())/1000)):m().minutes*60}
function show(x){s.screen=x;save();render()}
function render(){stop();A.innerHTML=page();bind();document.body.classList.toggle("access-active",["access","signin"].includes(s.screen));if(s.screen==="test"&&s.endAt)runTimer();if(s.screen==="break"&&s.breakEndAt)runBreak()}
function runTimer(){tick=setInterval(()=>{const r=rem(),n=document.getElementById("timer");if(n){n.textContent=fmt(r);n.classList.toggle("warning",r<=C.warnSec);n.classList.toggle("hidden",s.timerHidden&&r>C.warnSec)}if(r<=C.warnSec&&!s.warning[m().id]){s.warning[m().id]=true;save();warning()}if(r<=0)finishModule()},250)}
function runBreak(){tick=setInterval(()=>{const r=Math.max(0,Math.ceil((s.breakEndAt-Date.now())/1000)),n=document.getElementById("breakClock");if(n)n.textContent=fmt(r);if(r<=0){stop();s.breakEndAt=null;s.mi=2;s.qi=0;show("directions")}},250)}
function begin(){if(s.completed[m().id])return;s.endAt=Date.now()+m().minutes*60000;s.qi=0;s.timerHidden=false;s.lineReader=false;save();show("test")}
function routeNext(){if(m().id==="rw1")s.adaptive.rw=scoreMod("rw1")>=.7?"hard":"easy";if(m().id==="math1")s.adaptive.math=scoreMod("math1")>=.7?"hard":"easy";save()}
function same(v,k){const a=String(v).trim(),b=String(k).trim();if(!a||!b)return false;const na=Number(a),nb=Number(b);if(Number.isFinite(na)&&Number.isFinite(nb))return na===nb;return a.toLowerCase()===b.toLowerCase()}
function scoreMod(id){const a=B[id]||[];let good=0;a.forEach((x,i)=>{const v=s.answers[`${id}-${i}`];if(v!==undefined&&same(v,x.answer))good++});return a.length?good/a.length:0}
function finishModule(){stop();s.completed[m().id]=true;s.endAt=null;routeNext();if(m().id==="rw2"){s.mi=2;s.qi=0;s.breakEndAt=Date.now()+C.breakSec*1000;show("break");return}if(m().id==="math2"){s.submitted=true;s.screen="finish";save();render();return}s.mi++;s.qi=0;show("directions")}
function answer(v){s.answers[qkey()]=v;save();render();focusQ()}
function spr(v){s.answers[qkey()]=v.trim();save()}
function mark(){const k=qkey();s.marked[k]=!s.marked[k];save();render();focusQ()}
function eliminate(i){const k=qkey(),a=new Set(s.eliminated[k]||[]);a.has(i)?a.delete(i):a.add(i);s.eliminated[k]=[...a];save();render();focusQ()}
function note(){const k=qkey(),v=prompt("Add a note for this question:",s.notes[k]||"");if(v===null)return;s.notes[k]=v.trim();save();toast(v.trim()?"Note saved":"Note removed")}
function highlight(){const sel=getSelection(),t=sel?.toString().trim();if(!t)return toast("Select text in the passage first.");const k=qkey(),a=s.highlights[k]||[];if(!a.includes(t))a.push(t);s.highlights[k]=a.slice(-12);sel.removeAllRanges();save();toast("Highlight saved");render()}
function toast(t){let n=document.getElementById("toast");if(!n){n=document.createElement("div");n.id="toast";n.className="toast";document.body.append(n)}n.textContent=t;n.classList.add("show");clearTimeout(n._x);n._x=setTimeout(()=>n.classList.remove("show"),1600)}
function go(i){if(!bank()[i]||s.completed[m().id])return;s.qi=i;save();closeOverlays();render();focusQ()}
function next(){s.qi<bank().length-1?(s.qi++,save(),render(),focusQ()):review()}
function back(){if(s.qi>0){s.qi--;save();render();focusQ()}}
function focusQ(){setTimeout(()=>document.getElementById("questionPrompt")?.focus(),0)}
function warning(){closeOverlays();const n=document.createElement("div");n.className="modal-backdrop";n.innerHTML='<div class="modal warning-modal" role="dialog" aria-modal="true" aria-labelledby="warnTitle"><h3 id="warnTitle">5 minutes remaining</h3><p>Five minutes remain in this module. The timer must remain visible until the module ends.</p><div class="modal-actions"><button class="btn" id="dismissWarn">Continue</button></div></div>';document.body.append(n);n.querySelector("#dismissWarn").focus();n.querySelector("#dismissWarn").onclick=()=>n.remove()}
function tools(){closeTools();const n=document.createElement("div");n.id="toolPopover";n.className="tool-popover";const canHide=rem()>C.warnSec;n.innerHTML=`<div class="tool-head"><b>More</b><button id="closeTools" class="icon-btn" aria-label="Close menu">×</button></div><button class="tool-item" id="directionsBtn">Directions</button><button class="tool-item" id="helpTool">Help</button><button class="tool-item" id="shortcutsTool">Shortcuts</button><button class="tool-item" id="atTool">Assistive Technology</button>${m().section==="Reading and Writing"?'<button class="tool-item" id="hlTool">Highlight selection</button>':""}<button class="tool-item" id="noteTool">Note</button><button class="tool-item" id="lineTool">${s.lineReader?"Turn off line reader":"Line reader"}</button><button class="tool-item" id="timerTool">${s.timerHidden&&canHide?"Show timer":"Hide timer"}</button>${m().section==="Math"?'<button class="tool-item" id="calcTool">Calculator</button><button class="tool-item" id="refTool">Reference sheet</button>':""}<button class="tool-item" id="zoomOut">Zoom out</button><button class="tool-item" id="zoomIn">Zoom in</button><button class="tool-item danger" id="exitTool">Exit the exam</button>`;document.body.append(n);n.querySelector("#closeTools").onclick=closeTools;n.querySelector("#directionsBtn").onclick=()=>{closeTools();directionsModal()};n.querySelector("#helpTool").onclick=()=>{closeTools();window.AZAMAN_HELP?window.AZAMAN_HELP():toast("Press Ctrl + Alt + H for help.")};n.querySelector("#shortcutsTool").onclick=()=>{closeTools();window.AZAMAN_SHORTCUTS?window.AZAMAN_SHORTCUTS():toast("Press F1 to see keyboard shortcuts.")};n.querySelector("#atTool").onclick=()=>{closeTools();assistiveTech()};n.querySelector("#hlTool")?.addEventListener("click",()=>{closeTools();highlight()});n.querySelector("#noteTool").onclick=()=>{closeTools();note()};n.querySelector("#lineTool").onclick=()=>{s.lineReader=!s.lineReader;save();closeTools();render()};n.querySelector("#timerTool").onclick=()=>{if(!canHide){s.timerHidden=false;toast("The timer cannot be hidden with 5 minutes remaining.")}else s.timerHidden=!s.timerHidden;save();closeTools();render()};n.querySelector("#calcTool")?.addEventListener("click",()=>{closeTools();calculator()});n.querySelector("#refTool")?.addEventListener("click",()=>{closeTools();reference()});n.querySelector("#zoomOut").onclick=()=>zoom(-.05);n.querySelector("#zoomIn").onclick=()=>zoom(.05);n.querySelector("#exitTool").onclick=()=>{closeTools();exitConfirm()}}
function assistiveTech(){closeOverlays();const n=document.createElement("div");n.id="atModal";n.className="modal-backdrop";n.innerHTML=`<div class="modal" role="dialog" aria-modal="true" aria-labelledby="atTitle"><div class="modal-head"><h3 id="atTitle">Assistive Technology</h3><button class="icon-btn" id="closeAt" aria-label="Close">×</button></div><p>Bluebook works with supported assistive technologies, including screen readers, magnification software, and high contrast colors.</p><p class="small">If you need assistive technology on test day, talk to your school's SSD coordinator ahead of time.</p><div class="modal-actions"><button class="btn primary-action" id="closeAt2">Continue</button></div></div>`;document.body.append(n);n.querySelector("#closeAt").onclick=n.querySelector("#closeAt2").onclick=()=>n.remove();n.querySelector("#closeAt2").focus()}
function exitConfirm(){closeOverlays();const n=document.createElement("div");n.id="exitModal";n.className="modal-backdrop";n.innerHTML=`<div class="modal" role="dialog" aria-modal="true" aria-labelledby="exitTitle"><h3 id="exitTitle">Exit the exam?</h3><p>Your answers are saved locally, but exiting now ends this testing session.</p><div class="modal-actions"><button class="btn" id="cancelExit">Cancel</button><button class="btn primary-action" id="confirmExit">Exit</button></div></div>`;document.body.append(n);n.querySelector("#cancelExit").focus();n.querySelector("#cancelExit").onclick=()=>n.remove();n.querySelector("#confirmExit").onclick=()=>reset()}
function closeTools(){document.getElementById("toolPopover")?.remove()}
function toggleTimerHidden(){const canHide=rem()>C.warnSec;if(!canHide){s.timerHidden=false;toast("The timer cannot be hidden with 5 minutes remaining.");return}s.timerHidden=!s.timerHidden;save();render()}
function toggleEliminatorMode(){document.body.classList.toggle("option-eliminator-mode");document.getElementById("eliminatorBtn")?.setAttribute("aria-pressed",String(document.body.classList.contains("option-eliminator-mode")))}
function directionsModal(){closeOverlays();const x=m(),v=x.id==="rw2"?s.adaptive.rw:x.id==="math2"?s.adaptive.math:"";const n=document.createElement("div");n.id="directionsModal";n.className="modal-backdrop";n.innerHTML=`<div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><h3>${esc(x.section)} · ${esc(x.label)}</h3><button class="icon-btn" id="closeDirections" aria-label="Close directions">×</button></div><p>${x.count} questions · ${x.minutes} minutes${v?` · ${v==="hard"?"Advanced":"Standard"} module variant`:""}</p>${x.section==="Math"?'<p>Calculator and reference sheet are available in this module.</p>':'<p>Move between questions only within the active module. Answers save automatically.</p>'}<div class="modal-actions"><button class="btn primary-action" id="closeDirections2">Continue</button></div></div>`;document.body.append(n);n.querySelector("#closeDirections").onclick=n.querySelector("#closeDirections2").onclick=()=>n.remove();n.querySelector("#closeDirections2").focus()}
function closeOverlays(){closeTools();["calculatorPanel","referencePanel","reviewModal","directionsModal","atModal","exitModal"].forEach(id=>document.getElementById(id)?.remove())}
function zoom(d){const x=Number(getComputedStyle(document.documentElement).getPropertyValue("--zoom-scale")||1);document.documentElement.style.setProperty("--zoom-scale",Math.min(1.25,Math.max(.85,x+d)))}
function calculator(){closeOverlays();const n=document.createElement("div");n.id="calculatorPanel";n.className="overlay-panel";n.innerHTML='<div class="panel-head"><b>Calculator</b><button id="closeCalc" class="icon-btn">×</button></div><input id="calcDisplay" class="calc-display mono" readonly aria-label="Calculator display"><div class="calc-grid">'+["7","8","9","÷","4","5","6","×","1","2","3","−","0",".","(",")","+","⌫","=","C"].map(v=>`<button class="calc-key" data-calc="${v}">${v}</button>`).join("")+"</div>";document.body.append(n);let e="";const d=n.querySelector("#calcDisplay");n.querySelector("#closeCalc").onclick=()=>n.remove();n.querySelectorAll("[data-calc]").forEach(b=>b.onclick=()=>{const v=b.dataset.calc;if(v==="C")e="";else if(v==="⌫")e=e.slice(0,-1);else if(v==="="){try{e=String(calcEval(e))}catch(_){e="Error"}}else e=e==="Error"?v:e+v;d.value=e})}
function calcEval(e){const x=e.replaceAll("×","*").replaceAll("÷","/").replaceAll("−","-");if(!x||!/^[0-9+*/(). -]+$/.test(x))throw Error();const t=x.match(/\d+(?:\.\d+)?|[()+\-*/]/g)||[],o=[],st=[],p={"+":1,"-":1,"*":2,"/":2};for(const v of t)if(/^\d/.test(v))o.push(+v);else if(v==="(")st.push(v);else if(v===")"){while(st.length&&st.at(-1)!=="(")o.push(st.pop());if(st.pop()!=="(")throw Error()}else{while(st.length&&st.at(-1)!=="("&&p[st.at(-1)]>=p[v])o.push(st.pop());st.push(v)}while(st.length){if(st.at(-1)==="(")throw Error();o.push(st.pop())}const a=[];for(const v of o)if(typeof v==="number")a.push(v);else{const b=a.pop(),c=a.pop();if(b===undefined||c===undefined)throw Error();a.push({"+":c+b,"-":c-b,"*":c*b,"/":c/b}[v])}if(a.length!==1||!Number.isFinite(a[0]))throw Error();return a[0]}
function reference(){closeOverlays();const n=document.createElement("div");n.id="referencePanel";n.className="overlay-panel reference-panel";n.innerHTML='<div class="panel-head"><b>Reference sheet</b><button id="closeRef" class="icon-btn">×</button></div><h4>Common formulas</h4><p>Circle: C=2πr, A=πr²</p><p>Triangle: A=½bh</p><p>Rectangle: A=lw</p><p>Prism: V=lwh</p><p>Cylinder: V=πr²h</p><p>Pythagorean: a²+b²=c²</p><p>Slope: m=(y₂−y₁)/(x₂−x₁)</p><p>Distance: d=√((x₂−x₁)²+(y₂−y₁)²)</p>';document.body.append(n);n.querySelector("#closeRef").onclick=()=>n.remove()}

function review(){closeOverlays();const n=document.createElement("div");n.id="reviewModal";n.className="modal-backdrop";const a=bank(),sec=m().section,secNum=sec==="Math"?"2":"1";n.innerHTML=`<div class="modal review-modal" role="dialog" aria-modal="true" aria-labelledby="reviewTitle"><h2 id="reviewTitle">Check Your Work</h2><p class="small">On test day, you won't be able to move on to the next module until time expires. For these practice questions, you can click Next when you're ready to move on.</p><div class="review-card"><div class="review-head"><h3>Section ${secNum}: ${esc(sec)} Questions</h3><div class="review-legend"><span class="legend-item"><span class="legend-box" aria-hidden="true"></span> Unanswered</span><span class="legend-item"><span class="legend-ribbon" aria-hidden="true"></span> For Review</span></div></div><div class="review-grid" role="group" aria-label="Review questions">${a.map((_,i)=>`<button class="review-q ${answered(i)?"answered":""} ${marked(i)?"marked":""}" data-q="${i}" aria-label="Question ${i+1}${answered(i)?", answered":", unanswered"}${marked(i)?", marked for review":""}">${i+1}</button>`).join("")}</div></div><div class="modal-actions"><button class="btn pill-blue" id="closeReview">Back</button><button class="btn pill-blue primary" id="submitModule">Next</button></div></div>`;document.body.append(n);n.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>go(+b.dataset.q));n.querySelector("#closeReview").onclick=()=>n.remove();n.querySelector("#submitModule").onclick=()=>{n.remove();finishModule()}}
function source(x){let h=`<div class="source-label">${esc(x.domain||"Source")}</div>`;if(x.source?.title)h+=`<div class="source-title">${esc(x.source.title)}</div>`;if(x.source?.paragraphs?.length)h+=`<div class="passage">${x.source.paragraphs.map(p=>`<p>${esc(p)}</p>`).join("")}</div>`;else if(x.source?.table)h+=`<div class="data-table"><table><thead><tr>${x.source.table.headers.map(v=>`<th>${esc(v)}</th>`).join("")}</tr></thead><tbody>${x.source.table.rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;else h+='<div class="passage"><p>Use the information in the question to determine the best answer.</p></div>';const hs=s.highlights[qkey()]||[];if(hs.length)h+=`<div class="annotation-list"><b>Saved highlights</b>${hs.map(v=>`<span>“${esc(v)}”</span>`).join("")}</div>`;if(s.notes[qkey()])h+=`<div class="annotation-note"><b>Note:</b> ${esc(s.notes[qkey()])}</div>`;return h}
function choices(x){const v=s.answers[qkey()]||"",e=new Set(s.eliminated[qkey()]||[]);return`<div class="choices" role="radiogroup" aria-label="Answer choices">${x.options.map((o,i)=>`<div class="choice-wrap ${e.has(i)?"eliminated":""}"><button class="choice ${v===C.letters[i]?"selected":""}" data-answer="${C.letters[i]}" aria-pressed="${v===C.letters[i]}"><span class="choice-letter">${C.letters[i]}</span><span>${esc(o)}</span></button><button class="eliminate-btn" data-eliminate="${i}">${e.has(i)?"Restore":"Cross out"}</button></div>`).join("")}</div>`}
function shell(i){return`<div class="app-shell">${i}</div>`}
function starSvg(){return`<svg class="ico-star" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.5l2.8 6 6.2.8-4.5 4.3 1.2 6.4L12 16.9 6.3 20l1.2-6.4L3 9.3l6.2-.8z" fill="var(--color-star)"/></svg>`}
function ticketSvg(){return`<svg class="ico-btn" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v3a2 2 0 0 0 0 4v3a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-3a2 2 0 0 0 0-4z" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="M15 5v12" stroke="currentColor" stroke-width="1.2" stroke-dasharray="2 2"/></svg>`}
function chevSvg(){return`<svg class="ico-btn" viewBox="0 0 24 24" aria-hidden="true"><path d="M14.5 5l-7 7 7 7" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function eyeSvg(){return`<svg class="ico-btn" viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12z" fill="none" stroke="currentColor" stroke-width="1.6"/><circle cx="12" cy="12" r="3" fill="none" stroke="currentColor" stroke-width="1.6"/></svg>`}
function homeSvg(){return`<svg class="ico-btn" viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 11L12 4l8.5 7M6 10v9h12v-9" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function checkSvg(){return`<svg class="ico-check" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 6L9 17l-5-5" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function bookmarkSvg(filled){return`<svg class="ico-bookmark" viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3h10v18l-5-4-5 4z" fill="${filled?"currentColor":"none"}" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg>`}
function bluebookArt(){return`<svg viewBox="0 0 640 360" preserveAspectRatio="xMidYMid slice" fill="none" stroke="currentColor" stroke-width="4" stroke-linejoin="round" stroke-linecap="round"><rect x="60" y="110" width="220" height="140" rx="10"/><path d="M75 125h190v110H75z" stroke-opacity=".4"/><path d="M230 250v60" stroke-opacity=".4"/><circle cx="230" cy="230" r="34"/><path d="M223 230l5 5 9-11"/><rect x="330" y="60" width="120" height="90" rx="8"/><path d="M345 75h90M345 90h90M345 105h60" stroke-opacity=".5"/><rect x="480" y="180" width="110" height="120" rx="8"/><path d="M495 300V250l40-14 40 14v50" stroke-opacity=".8"/><path d="M495 240h80" stroke-opacity=".5"/><circle cx="90" cy="70" r="18" stroke-opacity=".6"/><path d="M82 70l5 5 10-11" stroke-opacity=".6"/><path d="M420 60l30 16v32l-30 16-30-16V76z" stroke-opacity=".5"/></svg>`}
function syncSubmit(){const b=document.getElementById("signinBtn");if(b)b.disabled=!(s.student.trim()&&s.email.trim())}
function access(){return`<main class="page access-page"><div class="access-art" aria-hidden="true">${bluebookArt()}</div><section class="signin-modal card compact"><div class="signin-brand">${starSvg()}<span class="brand-word">Bluebook</span></div><h1>Sign In</h1><button id="ticketBtn" class="btn cta-yellow wide">${ticketSvg()}Use a sign-in ticket from your school</button><div class="or-divider"><span>OR</span></div><button id="accountBtn" class="btn outline-btn wide">Sign in with a College Board student account</button><div class="signin-links"><button id="educatorLink" class="btn link small">I'm an educator</button><button id="helpLink" class="btn link small">Need help signing in?</button></div></section><p class="access-foot"><button id="resetBtn" class="btn link small">Reset local test state</button></p></main>`}
function signin(){const ok=!!(s.student&&s.student.trim())&&!!(s.email&&s.email.trim());return`<main class="page access-page"><div class="access-art" aria-hidden="true">${bluebookArt()}</div><section class="signin-modal card compact"><button id="backToSignin" class="btn link small back-link" aria-label="Back to sign in">${chevSvg()} Back</button><h1>Sign In with a Student Account</h1><div class="field"><label for="student">Full name</label><input id="student" class="text-input" maxlength="60" value="${esc(s.student)}" placeholder="Your full name" autocomplete="name"></div><div class="field"><label for="email">Email address</label><input id="email" class="text-input" type="email" maxlength="80" value="${esc(s.email)}" placeholder="you@example.com" autocomplete="email"></div><div class="field"><label for="password">Password</label><div class="pw-wrap"><input id="password" class="text-input" type="password" maxlength="80" autocomplete="current-password" placeholder="Your password"><button id="pwToggle" class="pw-toggle" type="button" aria-label="Show password" aria-pressed="false">${eyeSvg()}</button></div></div><div class="field-links"><button id="forgotLink" class="btn link small">Forgot password?</button></div><div class="btn-row"><button id="signinBtn" class="btn primary-action wide" ${ok?"":"disabled"}>Submit</button></div><div class="signin-footer"><button id="helpLink2" class="btn link small">Need help signing in?</button></div></section></main>`}
function yourtests(){return`<main class="page yourtests-page"><div class="yt-wrap"><div class="yt-account"><span class="yt-user">${esc(s.student)}</span><button id="signOutBtn" class="btn link small">Sign out</button></div><header class="yt-head"><h1>Your Tests</h1><div class="tab-toggle" role="tablist" aria-label="Test filter"><button class="tab-pill active" role="tab" aria-selected="true" id="tabActive">Active</button><button class="tab-pill" role="tab" aria-selected="false" id="tabPast">Past</button></div></header><section class="test-card"><h2 class="test-name">Digital SAT</h2><dl class="test-meta"><div class="meta-row"><dt>Date:</dt><dd>Sat, Oct 3, 2026</dd></div><div class="meta-row"><dt>Arrival Time:</dt><dd>7:45 a.m.</dd></div><div class="meta-row"><dt>Doors Close:</dt><dd>8:00 a.m.</dd></div></dl><p class="test-acc">Testing Accommodations: You have no approved accommodations for this test.</p><div class="test-divider"></div><div class="test-ready"><span class="ready-note">${checkSvg()} It's time to set up your exam.</span><button id="startSetupBtn" class="btn cta-yellow">Start Exam Setup</button></div></section></div></main>`}
function wiz(n,inner,next){return`<main class="page wizard-page"><header class="wiz-head"><button id="wizHelp" class="btn link small">? Help</button><button id="wizHome" class="btn link small">Return to Home ${homeSvg()}</button></header><section class="wiz-body"><div class="wiz-card card">${inner}</div></section><footer class="wiz-foot"><button id="wizBack" class="btn pill-outline" ${n===1?"disabled":""}>Back</button><div class="wiz-progress"><span class="wiz-step-label">Step ${n} of 10</span><div class="seg-bar" role="progressbar" aria-valuenow="${n}" aria-valuemin="1" aria-valuemax="10" aria-label="Check-in progress">${Array.from({length:10},(_,i)=>`<span class="seg ${i<n?"fill":""}"></span>`).join("")}</div></div><button id="wizNext" class="btn cta-yellow pill">${next}</button></footer></main>`}
function roomBoxes(){const code=(s.roomCode||"").toUpperCase();return Array.from({length:5},(_,i)=>`<input class="code-input room-digit" maxlength="1" inputmode="text" data-pos="${i}" aria-label="Room code letter ${i+1}" value="${esc(code[i]||"")}" autocomplete="off">`).join("")}
function startBoxes(){const code=s.startCode||"";return Array.from({length:6},(_,i)=>`<input class="code-input start-digit" maxlength="1" inputmode="numeric" data-pos="${i}" aria-label="Start code digit ${i+1}" value="${esc(code[i]||"")}" autocomplete="off">`).join("")}
function checkin(){const n=s.step||1;switch(n){case 1:return wiz(1,`<h1>Welcome, ${esc((s.student||"student").split(" ")[0])}.</h1><p>You're signed in and ready to complete check-in for the Digital SAT. Follow the next few steps to finish setting up your test.</p><p class="small muted">Digital SAT · 2 sections · 4 modules</p>`,"Get Started");
case 2:return wiz(2,`<h1>Your Info</h1><p>Confirm that this information is correct before you continue.</p><dl class="info-rows"><div class="info-row"><dt>Name</dt><dd>${esc(s.student)}</dd></div><div class="info-row"><dt>Email</dt><dd>${esc(s.email)}</dd></div><div class="info-row"><dt>Test</dt><dd>Digital SAT</dd></div></dl><label class="ack"><input id="infoAck" type="checkbox" ${s.infoOk?"checked":""}> <span>The information above is correct.</span></label>`,"Next");
case 3:{const code=(s.roomCode||"").toUpperCase(),full=code.length===5,good=full&&["AZM24","AZMPR"].includes(code);return wiz(3,`<h1>Room Code</h1><p>Enter your room code now to complete check-in.</p><p class="small muted">The room code contains <strong>letters</strong> only.</p><div class="code-row" aria-label="Room code">${roomBoxes()}</div>${good?`<p class="success-msg">${checkSvg()} Success! Click the Next button to complete check-in.</p>`:full?`<p class="error-msg" role="alert">That code isn't right. Check with your proctor and try again.</p>`:""}`,"Next")}
case 4:return wiz(4,`<h1>Accommodations</h1><p>Testing Accommodations: You have no approved accommodations for this test.</p><p class="small muted">If you're approved for accommodations, they'll be listed here once your school confirms them.</p>`,"Next");
case 5:{const aids=[["sr","Screen reader availability"],["mag","Magnification software"],["contrast","High contrast colors"]];return wiz(5,`<h1>Accessibility Aids</h1><p>Select any assistive technology you plan to use during testing.</p>${aids.map(([k,label])=>`<label class="ack"><input type="checkbox" class="aid-check" data-aid="${k}" ${(s.aids||{})[k]?"checked":""}> <span>${label}</span></label>`).join("")}<p class="small muted">You can also change these later from the More menu during the test.</p>`,"Next")}
case 6:return wiz(6,`<h1>Equipment Check</h1><p>Bluebook checked your device and it's ready for testing.</p><ul class="check-list">${["Battery level — Good","Internet connection — Connected","Application — Up to date"].map(t=>`<li class="check-ok">${checkSvg()} ${t}</li>`).join("")}</ul>`,"Next");
case 7:return wiz(7,`<h1>Testing Rules</h1><p>Before testing begins, you must agree to follow all rules for the exam. Read the <strong>SAT Weekend Testing Rules</strong> carefully.</p><ul class="rules-list"><li>Work only on the section being tested.</li><li>Don't share test questions or answers with anyone.</li><li>Keep your device on and open for the entire test.</li></ul><label class="ack"><input id="deskAck" type="checkbox" ${s.desk?"checked":""}> <span>I have cleared my workspace.</span></label><div class="field"><label for="pledge">Type the statement below to confirm you agree:</label><p class="pledge-quote">I agree to follow all rules for this test.</p><input id="pledge" class="text-input" value="${esc(s.pledge)}" autocomplete="off" placeholder="Type I agree"></div>`,"Next");
case 8:return wiz(8,`<h1>Start Code</h1><p>Your proctor will read the start code aloud. Enter it to begin testing.</p><div class="code-row" aria-label="Start code">${startBoxes()}</div>`,"Next");
case 9:return wiz(9,`<h1>Directions</h1><p>The SAT has 2 sections. Each section has 2 separately timed modules.</p><dl class="info-rows"><div class="info-row"><dt>Reading and Writing</dt><dd>2 modules · 32 minutes each</dd></div><div class="info-row"><dt>Math</dt><dd>2 modules · 35 minutes each</dd></div></dl><p>You'll get one 10-minute break after Reading and Writing. A calculator and reference sheet are available in the Math sections. Your answers save automatically.</p>`,"Next");
default:return wiz(10,`<h1>You're checked in.</h1><p>When your proctor tells you to begin, select Start Test. Good luck, ${esc((s.student||"student").split(" ")[0])}!</p>`,"Start Test")}}
function directions(){const x=m(),isMath=x.section==="Math",v=x.id==="rw2"?s.adaptive.rw:x.id==="math2"?s.adaptive.math:"";return`<main class="page"><section class="card compact center-card"><h1>Directions</h1><p><strong>${esc(x.section)} — ${esc(x.label)}</strong></p><p>${x.count} questions · ${x.minutes} minutes${v?` · ${v==="hard"?"Advanced":"Standard"} module variant`:""}</p>${isMath?'<p>A calculator and the reference sheet are available in this module.</p>':'<p>Move between questions only within the active module. Your answers save automatically.</p>'}<div class="btn-row center-row"><button id="beginModuleBtn" class="btn pill-blue primary">Start</button></div></section></main>`}
function test(){const x=q(),r=rem(),hide=s.timerHidden&&r>C.warnSec,secNum=m().section==="Math"?"2":"1",math=m().section==="Math",last=s.qi===m().count-1;return`<div class="test-shell"><header class="test-top"><div class="test-title">${secNum}: ${esc(m().section)}</div><div class="timer-block"><div id="timer" class="timer ${r<=C.warnSec?"warning":""} ${hide?"hidden":""}" aria-live="polite">${fmt(r)}</div>${r>C.warnSec?`<button id="hideTimerBtn" class="timer-hide" aria-pressed="${String(!!s.timerHidden)}">${s.timerHidden?"Show":"Hide"}</button>`:""}</div><div class="top-tools">${math?`<button id="calcToolBtn" class="nav-pill">Calculator</button><button id="refToolBtn" class="nav-pill">Reference</button>`:`<button id="notesToolBtn" class="nav-pill">Highlights &amp; Notes</button>`}<button id="toolsBtn" class="nav-pill">More</button></div></header><main class="test-main"><section class="source-panel">${source(x)}</section><section class="question-panel"><div class="question-card"><div class="q-head"><span class="q-number">${s.qi+1}</span><button id="markBtn" class="mark-pill ${marked()?"active":""}" aria-pressed="${String(marked())}" aria-label="Mark for review">${bookmarkSvg(marked())} Mark for Review</button><button id="eliminatorBtn" class="elim-badge" aria-pressed="${String(document.body.classList.contains("option-eliminator-mode"))}" title="Option eliminator">ABC</button></div><h2 id="questionPrompt" class="q-prompt" tabindex="-1">${esc(x.prompt)}</h2>${x.type==="spr"?`<div class="spr-wrap"><label for="spr">Enter your answer</label><input id="spr" class="spr-input mono" inputmode="decimal" value="${esc(s.answers[qkey()]||"")}" placeholder="Answer"></div>`:choices(x)}</div></section></main><footer class="test-footer"><div class="footer-left"><span class="footer-name">${esc(s.student)}</span>${s.notes[qkey()]?'<span class="annotation-chip">Note saved</span>':""}</div><div class="footer-center"><button id="reviewBtn" class="question-nav" aria-haspopup="dialog" aria-label="Question menu">Question ${s.qi+1} of ${m().count} <span class="caret" aria-hidden="true">&#9662;</span></button></div><div class="footer-right"><button id="prevBtn" class="btn pill-blue" ${s.qi===0?"disabled":""}>Back</button><button id="nextBtn" class="btn pill-blue primary">${last?"Review module":"Next"}</button></div></footer>${s.lineReader?'<div class="line-reader" aria-hidden="true"></div>':""}</div>`}
function breakPage(){return`<main class="page"><section class="card compact center-card"><div class="kicker">Section 1 complete</div><h1>This Section Is Over</h1><p>Reading and Writing is complete. Take a break — Math will start when the break ends.</p><div id="breakClock" class="break-clock">${fmt(Math.max(0,Math.ceil((s.breakEndAt-Date.now())/1000)))}</div><p class="small">You cannot advance early. The timer continues automatically.</p></section></main>`}
function finish(){const z=scoreAll();return`<main class="page finish-page"><div class="finish-confetti" aria-hidden="true"></div><section class="card compact center-card congrats-card"><h1>Congratulations!</h1><p class="congrats-sub">The test is complete, and your answers have been submitted.</p><div class="congrats-split"><div class="congrats-art">${laptopArt()}</div><div class="congrats-text"><p>Your proctor will dismiss you when it's time to go.</p><p>Please <strong>be quiet</strong>; other students may still be testing.</p></div></div></section><section class="card compact center-card"><div class="kicker">Practice complete</div><h2>Practice score</h2><p class="small">Responses are saved locally. This practice simulator does not submit results to College Board.</p><div class="info-grid"><div class="info-box"><div class="value">${z.correct}</div><div class="label">Correct</div></div><div class="info-box"><div class="value">${z.answered}</div><div class="label">Answered</div></div><div class="info-box"><div class="value">98</div><div class="label">Questions</div></div><div class="info-box"><div class="value">${z.pct}%</div><div class="label">Accuracy</div></div></div><div class="btn-row center-row"><button id="restartBtn" class="btn cta-yellow">Return to Homepage</button></div></section></main>`}
function laptopArt(){return`<svg viewBox="0 0 120 100" role="img" aria-label="Illustration of a smiling laptop"><rect x="18" y="12" width="84" height="58" rx="6" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="60" cy="41" r="15" fill="none" stroke="currentColor" stroke-width="3"/><path d="M53 41 q3.5 4 7 0" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><path d="M63 41 q3.5 4 7 0" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><path d="M53 47 q7 5 14 0" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><path d="M10 74 h100 l6 9 H4 z" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/></svg>`}
function scoreAll(){let correct=0,answeredN=0;C.mods.forEach(x=>{const a=x.id==="rw2"?B.rw2?.[s.adaptive.rw]||[]:x.id==="math2"?B.math2?.[s.adaptive.math]||[]:B[x.bank]||[];a.forEach((q,i)=>{const v=s.answers[`${x.id}-${i}`];if(v!==undefined&&String(v).trim()!==""){answeredN++;if(same(v,q.answer))correct++}})});return{correct,answered:answeredN,pct:Math.round(correct/98*100)}}
function page(){switch(s.screen){case"access":return shell(access());case"signin":return shell(signin());case"yourtests":return shell(yourtests());case"checkin":return shell(checkin());case"directions":return shell(directions());case"test":return test();case"break":return shell(breakPage());case"finish":return shell(finish());default:return shell(access())}}
function bind(){
if(s.screen==="access"){document.getElementById("ticketBtn")?.addEventListener("click",()=>{s.ticket=true;save();show("signin")});document.getElementById("accountBtn")?.addEventListener("click",()=>{s.ticket=false;save();show("signin")});document.getElementById("educatorLink")?.addEventListener("click",()=>toast("Educator sign-in is available in Test Day Toolkit."));document.getElementById("helpLink")?.addEventListener("click",()=>toast("Ask your school's test coordinator if you need help signing in."));document.getElementById("resetBtn")?.addEventListener("click",()=>reset())}
if(s.screen==="signin"){document.getElementById("student")?.addEventListener("input",e=>{s.student=e.target.value;save();syncSubmit()});document.getElementById("email")?.addEventListener("input",e=>{s.email=e.target.value;save();syncSubmit()});const pw=document.getElementById("password");pw?.addEventListener("input",e=>{s.password=e.target.value;save()});document.getElementById("pwToggle")?.addEventListener("click",()=>{if(!pw)return;const show=pw.type==="password";pw.type=show?"text":"password";const b=document.getElementById("pwToggle");b.setAttribute("aria-pressed",String(show));b.setAttribute("aria-label",show?"Hide password":"Show password")});document.getElementById("backToSignin")?.addEventListener("click",()=>show("access"));document.getElementById("forgotLink")?.addEventListener("click",()=>toast("Password reset isn't available in this practice simulator."));document.getElementById("helpLink2")?.addEventListener("click",()=>toast("Ask your school's test coordinator if you need help signing in."));document.getElementById("signinBtn")?.addEventListener("click",()=>{if(!(s.student||"").trim())return toast("Enter your full name.");if(!(s.email||"").trim())return toast("Enter your email address.");show("yourtests")});setTimeout(()=>pw?.focus(),0)}
if(s.screen==="yourtests"){document.getElementById("startSetupBtn")?.addEventListener("click",()=>{s.step=1;save();show("checkin")});document.getElementById("signOutBtn")?.addEventListener("click",()=>reset());document.getElementById("tabActive")?.addEventListener("click",()=>toast("You have 1 active test."));document.getElementById("tabPast")?.addEventListener("click",()=>toast("You have no past tests."))}
if(s.screen==="checkin"){document.getElementById("wizHelp")?.addEventListener("click",()=>toast("Ask your proctor for help with this step."));document.getElementById("wizHome")?.addEventListener("click",()=>show("yourtests"));document.getElementById("infoAck")?.addEventListener("change",e=>{s.infoOk=e.target.checked;save()});document.querySelectorAll(".room-digit").forEach(x=>{x.addEventListener("input",e=>{const v=e.target.value.replace(/[^a-zA-Z]/g,"").toUpperCase().slice(-1);e.target.value=v;const i=+e.target.dataset.pos;s.roomCode=Array.from(document.querySelectorAll(".room-digit")).map(z=>z.value).join("");if(v&&i<4)document.querySelectorAll(".room-digit")[i+1]?.focus();save();if(s.roomCode.length===5)render()});x.addEventListener("keydown",e=>{if(e.key==="Backspace"&&!e.target.value){const i=+e.target.dataset.pos;if(i>0){document.querySelectorAll(".room-digit")[i-1]?.focus();e.preventDefault()}}});x.addEventListener("focus",()=>x.select())});document.querySelectorAll(".aid-check").forEach(x=>x.addEventListener("change",e=>{s.aids=s.aids||{};s.aids[e.target.dataset.aid]=e.target.checked;save()}));document.getElementById("deskAck")?.addEventListener("change",e=>{s.desk=e.target.checked;save()});document.getElementById("pledge")?.addEventListener("input",e=>{s.pledge=e.target.value;s.rules=s.pledge.trim().toLowerCase().replace(/[.!]$/,"")==="i agree";save()});document.querySelectorAll(".start-digit").forEach(x=>{x.addEventListener("input",e=>{const v=e.target.value.replace(/\D/g,"").slice(-1);e.target.value=v;const i=+e.target.dataset.pos;s.startCode=Array.from(document.querySelectorAll(".start-digit")).map(z=>z.value).join("");if(v&&i<5)document.querySelectorAll(".start-digit")[i+1]?.focus();save()});x.addEventListener("keydown",e=>{if(e.key==="Backspace"&&!e.target.value){const i=+e.target.dataset.pos;if(i>0){document.querySelectorAll(".start-digit")[i-1]?.focus();e.preventDefault()}}});x.addEventListener("focus",()=>x.select())});document.getElementById("wizBack")?.addEventListener("click",()=>{s.step=Math.max(1,(s.step||1)-1);save();render()});document.getElementById("wizNext")?.addEventListener("click",()=>{const n=s.step||1;if(n===3){const rc=(s.roomCode||"").toUpperCase();if(rc.length<5)return toast("Enter the 5-letter room code.");if(!["AZM24","AZMPR"].includes(rc))return toast("Invalid room code. Check with your proctor and try again.");s.roomCode=C.roomCode}if(n===7){if(!s.rules)return toast("Type the agreement statement to continue.");if(!s.desk)return toast("Confirm you have cleared your workspace.")}if(n===8){if((s.startCode||"").length<6)return toast("Enter the 6-digit start code.");if(s.startCode!==C.startCode)return toast("Invalid start code. Listen carefully and try again.")}if(n===10){show("directions");return}s.step=n+1;save();render()})}
if(s.screen==="directions"){document.getElementById("beginModuleBtn")?.addEventListener("click",begin)}
if(s.screen==="test"){document.getElementById("directionsBtn")?.addEventListener("click",directionsModal);document.getElementById("toolsBtn")?.addEventListener("click",tools);document.getElementById("hideTimerBtn")?.addEventListener("click",toggleTimerHidden);document.getElementById("notesToolBtn")?.addEventListener("click",()=>note());document.getElementById("calcToolBtn")?.addEventListener("click",()=>calculator());document.getElementById("refToolBtn")?.addEventListener("click",()=>reference());document.getElementById("eliminatorBtn")?.addEventListener("click",toggleEliminatorMode);document.getElementById("markBtn")?.addEventListener("click",mark);document.getElementById("reviewBtn")?.addEventListener("click",review);document.getElementById("prevBtn")?.addEventListener("click",back);document.getElementById("nextBtn")?.addEventListener("click",next);document.querySelectorAll(".choice").forEach(x=>x.addEventListener("click",()=>answer(x.dataset.answer)));document.querySelectorAll(".eliminate-btn").forEach(x=>x.addEventListener("click",()=>eliminate(+x.dataset.eliminate)));document.getElementById("spr")?.addEventListener("input",e=>spr(e.target.value));document.getElementById("spr")?.addEventListener("blur",e=>{spr(e.target.value);render()})}
if(s.screen==="finish")document.getElementById("restartBtn")?.addEventListener("click",()=>reset())}
function reset(){stop();localStorage.removeItem(C.storageKey);location.reload()}
render();window.AZAMAN_APP={getState:()=>s,save,render,scoreAll,same};})();