(()=>{"use strict";
const C={storageKey:"azaman-sat-practice-v3",accessCodes:["SAT26","PRACTICE","AZM-SAT"],roomCode:"AZM24",startCode:"492776",breakSec:600,warnSec:300,mods:[
{id:"rw1",section:"Reading and Writing",label:"Module 1",minutes:32,count:27,bank:"rw1"},{id:"rw2",section:"Reading and Writing",label:"Module 2",minutes:32,count:27,bank:"rw2"},{id:"math1",section:"Math",label:"Module 1",minutes:35,count:22,bank:"math1"},{id:"math2",section:"Math",label:"Module 2",minutes:35,count:22,bank:"math2"}],letters:["A","B","C","D"]};
const A=document.getElementById("app"),B=window.SAT_QUESTIONS||{};let s=load()||fresh(),tick=null;
function fresh(){return{v:3,screen:"access",student:"",accessCode:"",roomCode:"",startCode:"",mi:0,qi:0,endAt:null,breakEndAt:null,answers:{},marked:{},eliminated:{},notes:{},highlights:{},completed:{},submitted:false,adaptive:{rw:"easy",math:"easy"},timerHidden:false,lineReader:false,rules:false,desk:false,warning:{}}}
function load(){try{const x=JSON.parse(localStorage.getItem(C.storageKey));return x?.v===3?x:null}catch(_){return null}}
function save(){try{localStorage.setItem(C.storageKey,JSON.stringify(s))}catch(_){} }
function stop(){if(tick)clearInterval(tick);tick=null}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function m(){return C.mods[s.mi]}
function bank(){const x=m();return x.id==="rw2"?B.rw2?.[s.adaptive.rw]||[]:x.id==="math2"?B.math2?.[s.adaptive.math]||[]:B[x.bank]||[]}
function q(){return bank()[s.qi]||{prompt:"Question unavailable",options:["A","B","C","D"],answer:"A",domain:"Unknown",skill:"Unknown",difficulty:"medium"}}
function qkey(i=s.qi){return`${m().id}-${i}`}
function answered(i=s.qi){return s.answers[qkey(i)]!==undefined&&s.answers[qkey(i)]!==""}
function marked(i=s.qi){return!!s.marked[qkey(i)]}
function fmt(x){x=Math.max(0,Math.floor(x));return`${String(Math.floor(x/60)).padStart(2,"0")}:${String(x%60).padStart(2,"0")}`}
function rem(){return s.endAt?Math.max(0,Math.ceil((s.endAt-Date.now())/1000)):m().minutes*60}
function show(x){s.screen=x;save();render()}
function render(){stop();A.innerHTML=page();bind();if(s.screen==="test"&&s.endAt)runTimer();if(s.screen==="break"&&s.breakEndAt)runBreak()}
function runTimer(){tick=setInterval(()=>{const r=rem(),n=document.getElementById("timer");if(n){n.textContent=fmt(r);n.classList.toggle("warning",r<=C.warnSec);n.classList.toggle("hidden",s.timerHidden&&r>C.warnSec)}if(r===C.warnSec&&!s.warning[m().id]){s.warning[m().id]=true;save();warning()}if(r<=0)finishModule()},250)}
function runBreak(){tick=setInterval(()=>{const r=Math.max(0,Math.ceil((s.breakEndAt-Date.now())/1000)),n=document.getElementById("breakClock");if(n)n.textContent=fmt(r);if(r<=0){stop();s.breakEndAt=null;s.mi=2;s.qi=0;show("directions")}},250)}
function begin(){if(s.completed[m().id])return;s.endAt=Date.now()+m().minutes*60000;s.qi=0;s.timerHidden=false;s.lineReader=false;save();show("test")}
function routeNext(){if(m().id==="rw1")s.adaptive.rw=scoreMod("rw1")>=.7?"hard":"easy";if(m().id==="math1")s.adaptive.math=scoreMod("math1")>=.7?"hard":"easy";save()}
function scoreMod(id){const a=B[id]||[];let good=0;a.forEach((x,i)=>{const v=s.answers[`${id}-${i}`];if(v!==undefined&&String(v).trim().toLowerCase()===String(x.answer).trim().toLowerCase())good++});return a.length?good/a.length:0}
function finishModule(){stop();s.completed[m().id]=true;s.endAt=null;routeNext();if(m().id==="rw2"){s.mi=2;s.qi=0;s.breakEndAt=Date.now()+C.breakSec*1000;show("break");return}if(m().id==="math2"){s.submitted=true;s.screen="finish";save();render();return}s.mi++;s.qi=0;show("directions")}
function answer(v){s.answers[qkey()]=v;save();render();focusQ()}
function spr(v){s.answers[qkey()]=v.trim();save()}
function mark(){const k=qkey();s.marked[k]=!s.marked[k];save();render();focusQ()}
function eliminate(i){const k=qkey(),a=new Set(s.eliminated[k]||[]);a.has(i)?a.delete(i):a.add(i);s.eliminated[k]=[...a];save();render();focusQ()}
function note(){const k=qkey(),v=prompt("Add a note for this question:",s.notes[k]||"");if(v===null)return;s.notes[k]=v.trim();save();toast(v.trim()?"Note saved":"Note removed")}
function highlight(){const sel=getSelection(),t=sel?.toString().trim();if(!t)return toast("Select text in the passage first.");const k=qkey(),a=s.highlights[k]||[];if(!a.includes(t))a.push(t);s.highlights[k]=a.slice(-12);sel.removeAllRanges();save();toast("Highlight saved");render()}
function toast(t){let n=document.getElementById("toast");if(!n){n=document.createElement("div");n.id="toast";n.className="toast";document.body.append(n)}n.textContent=t;n.classList.add("show");clearTimeout(n._x);n._x=setTimeout(()=>n.classList.remove("show"),1600)}
function go(i){if(!bank()[i]||s.completed[m().id])return;s.qi=i;save();closeOverlays();render();focusQ()}
function next(){s.qi<bank().length-1?(s.qi++,save(),render(),focusQ()):review()}
function back(){if(s.qi>0){s.qi--;save();render();focusQ()}}
function focusQ(){setTimeout(()=>document.getElementById("questionPrompt")?.focus(),0)}
function warning(){closeOverlays();const n=document.createElement("div");n.className="modal-backdrop";n.innerHTML='<div class="modal warning-modal" role="dialog" aria-modal="true" aria-labelledby="warnTitle"><h3 id="warnTitle">5 minutes remaining</h3><p>Five minutes remain in this module. The timer must remain visible until the module ends.</p><div class="modal-actions"><button class="btn" id="dismissWarn">Continue</button></div></div>';document.body.append(n);n.querySelector("#dismissWarn").focus();n.querySelector("#dismissWarn").onclick=()=>n.remove()}
function review(){closeOverlays();const n=document.createElement("div");n.id="reviewModal";n.className="modal-backdrop";const a=bank(),u=a.filter((_,i)=>!answered(i)).length,f=a.filter((_,i)=>marked(i)).length;n.innerHTML=`<div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><h3>Review questions</h3><button class="icon-btn" id="closeReview">×</button></div><p class="small">Answered: ${a.length-u} · Unanswered: ${u} · Marked: ${f}</p><div class="review-grid">${a.map((_,i)=>`<button class="review-q ${answered(i)?"answered":""} ${marked(i)?"marked":""}" data-q="${i}">${i+1}</button>`).join("")}</div><div class="modal-actions"><button class="btn" id="closeReview2">Back</button><button class="btn primary-action" id="submitModule">Finish module</button></div></div>`;document.body.append(n);n.querySelectorAll("[data-q]").forEach(b=>b.onclick=()=>go(+b.dataset.q));n.querySelector("#closeReview").onclick=n.querySelector("#closeReview2").onclick=()=>n.remove();n.querySelector("#submitModule").onclick=()=>{n.remove();finishModule()}}
function tools(){closeTools();const n=document.createElement("div");n.id="toolPopover";n.className="tool-popover";const canHide=rem()>C.warnSec;n.innerHTML=`<div class="tool-head"><b>Test tools</b><button id="closeTools" class="icon-btn">×</button></div><button class="tool-item" id="noteTool">Note</button>${m().section==="Reading and Writing"?'<button class="tool-item" id="hlTool">Highlight selection</button>':""}<button class="tool-item" id="lineTool">${s.lineReader?"Turn off line reader":"Line reader"}</button><button class="tool-item" id="timerTool">${s.timerHidden&&canHide?"Show timer":"Hide timer"}</button>${m().section==="Math"?'<button class="tool-item" id="calcTool">Calculator</button><button class="tool-item" id="refTool">Reference sheet</button>':""}<button class="tool-item" id="zoomOut">Zoom out</button><button class="tool-item" id="zoomIn">Zoom in</button>`;document.body.append(n);n.querySelector("#closeTools").onclick=closeTools;n.querySelector("#noteTool").onclick=()=>{closeTools();note()};n.querySelector("#hlTool")?.addEventListener("click",()=>{closeTools();highlight()});n.querySelector("#lineTool").onclick=()=>{s.lineReader=!s.lineReader;save();closeTools();render()};n.querySelector("#timerTool").onclick=()=>{if(!canHide){s.timerHidden=false;toast("The timer cannot be hidden with 5 minutes remaining.")}else s.timerHidden=!s.timerHidden;save();closeTools();render()};n.querySelector("#calcTool")?.addEventListener("click",()=>{closeTools();calculator()});n.querySelector("#refTool")?.addEventListener("click",()=>{closeTools();reference()});n.querySelector("#zoomOut").onclick=()=>zoom(-.05);n.querySelector("#zoomIn").onclick=()=>zoom(.05)}
function closeTools(){document.getElementById("toolPopover")?.remove()}
function closeOverlays(){closeTools();["calculatorPanel","referencePanel","reviewModal"].forEach(id=>document.getElementById(id)?.remove())}
function zoom(d){const x=Number(getComputedStyle(document.documentElement).getPropertyValue("--zoom-scale")||1);document.documentElement.style.setProperty("--zoom-scale",Math.min(1.25,Math.max(.85,x+d)))}
function calculator(){closeOverlays();const n=document.createElement("div");n.id="calculatorPanel";n.className="overlay-panel";n.innerHTML='<div class="panel-head"><b>Calculator</b><button id="closeCalc" class="icon-btn">×</button></div><input id="calcDisplay" class="calc-display mono" readonly aria-label="Calculator display"><div class="calc-grid">'+["7","8","9","÷","4","5","6","×","1","2","3","−","0",".","(",")","+","⌫","=","C"].map(v=>`<button class="calc-key" data-calc="${v}">${v}</button>`).join("")+"</div>";document.body.append(n);let e="";const d=n.querySelector("#calcDisplay");n.querySelector("#closeCalc").onclick=()=>n.remove();n.querySelectorAll("[data-calc]").forEach(b=>b.onclick=()=>{const v=b.dataset.calc;if(v==="C")e="";else if(v==="⌫")e=e.slice(0,-1);else if(v==="="){try{e=String(calcEval(e))}catch(_){e="Error"}}else e=e==="Error"?v:e+v;d.value=e})}
function calcEval(e){const x=e.replaceAll("×","*").replaceAll("÷","/").replaceAll("−","-");if(!x||!/^[0-9+*/(). -]+$/.test(x))throw Error();const t=x.match(/\d+(?:\.\d+)?|[()+\-*/]/g)||[],o=[],st=[],p={"+":1,"-":1,"*":2,"/":2};for(const v of t)if(/^\d/.test(v))o.push(+v);else if(v==="(")st.push(v);else if(v===")"){while(st.length&&st.at(-1)!=="(")o.push(st.pop());if(st.pop()!=="(")throw Error()}else{while(st.length&&st.at(-1)!=="("&&p[st.at(-1)]>=p[v])o.push(st.pop());st.push(v)}while(st.length){if(st.at(-1)==="(")throw Error();o.push(st.pop())}const a=[];for(const v of o)if(typeof v==="number")a.push(v);else{const b=a.pop(),c=a.pop();if(b===undefined||c===undefined)throw Error();a.push({"+":c+b,"-":c-b,"*":c*b,"/":c/b}[v])}if(a.length!==1||!Number.isFinite(a[0]))throw Error();return a[0]}
function reference(){closeOverlays();const n=document.createElement("div");n.id="referencePanel";n.className="overlay-panel reference-panel";n.innerHTML='<div class="panel-head"><b>Reference sheet</b><button id="closeRef" class="icon-btn">×</button></div><h4>Common formulas</h4><p>Circle: C=2πr, A=πr²</p><p>Triangle: A=½bh</p><p>Rectangle: A=lw</p><p>Prism: V=lwh</p><p>Cylinder: V=πr²h</p><p>Pythagorean: a²+b²=c²</p><p>Slope: m=(y₂−y₁)/(x₂−x₁)</p><p>Distance: d=√((x₂−x₁)²+(y₂−y₁)²)</p>';document.body.append(n);n.querySelector("#closeRef").onclick=()=>n.remove()}
function source(x){let h=`<div class="source-label">${esc(x.domain||"Source")}</div>`;if(x.source?.title)h+=`<div class="source-title">${esc(x.source.title)}</div>`;if(x.source?.paragraphs?.length)h+=`<div class="passage">${x.source.paragraphs.map(p=>`<p>${esc(p)}</p>`).join("")}</div>`;else if(x.source?.table)h+=`<div class="data-table"><table><thead><tr>${x.source.table.headers.map(v=>`<th>${esc(v)}</th>`).join("")}</tr></thead><tbody>${x.source.table.rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;else h+='<div class="passage"><p>Use the information in the question to determine the best answer.</p></div>';const hs=s.highlights[qkey()]||[];if(hs.length)h+=`<div class="annotation-list"><b>Saved highlights</b>${hs.map(v=>`<span>“${esc(v)}”</span>`).join("")}</div>`;if(s.notes[qkey()])h+=`<div class="annotation-note"><b>Note:</b> ${esc(s.notes[qkey()])}</div>`;return h}
function choices(x){const v=s.answers[qkey()]||"",e=new Set(s.eliminated[qkey()]||[]);return`<div class="choices" role="radiogroup" aria-label="Answer choices">${x.options.map((o,i)=>`<div class="choice-wrap ${e.has(i)?"eliminated":""}"><button class="choice ${v===C.letters[i]?"selected":""}" data-answer="${C.letters[i]}" aria-pressed="${v===C.letters[i]}"><span class="choice-letter">${C.letters[i]}</span><span>${esc(o)}</span></button><button class="eliminate-btn" data-eliminate="${i}">${e.has(i)?"Restore":"Cross out"}</button></div>`).join("")}</div>`}
function shell(i){return`<div class="app-shell"><header class="topbar"><div class="brand"><div class="brand-mark">AZ</div><div class="brand-name">Azaman SAT Practice</div></div><div class="topbar-right">${s.student?`<span class="topbar-student">${esc(s.student)}</span>`:""}</div></header>${i}</div>`}
function access(){return`<main class="page"><section class="card compact"><div class="kicker">Practice exam</div><h1>Sign in</h1><p>Use the practice access code supplied for this session.</p><div class="field"><label for="access">Access code</label><input id="access" class="text-input center mono" maxlength="12" value="${esc(s.accessCode)}" placeholder="SAT26"></div><div class="field"><label for="student">Name shown during testing</label><input id="student" class="text-input" maxlength="60" value="${esc(s.student)}" placeholder="Your name"></div><div class="btn-row"><button id="accessBtn" class="btn wide">Continue</button></div><p class="small">Demo codes: SAT26, PRACTICE, AZM-SAT</p><div class="divider"></div><button id="resetBtn" class="btn link small">Reset local test state</button></section></main>`}
function checkin(){return`<main class="page"><section class="card"><div class="kicker">Test-day setup</div><h2>Before you test</h2><div class="info-grid"><div class="info-box"><div class="value">98</div><div class="label">Questions</div></div><div class="info-box"><div class="value">134</div><div class="label">Testing minutes</div></div><div class="info-box"><div class="value">10:00</div><div class="label">Break</div></div><div class="info-box"><div class="value">4</div><div class="label">Modules</div></div></div><ul class="check-list"><li>Keep your workspace clear.</li><li>Move between questions only within the active module.</li><li>Answers save automatically.</li><li>Completed modules are locked.</li></ul><label class="ack"><input id="rulesAck" type="checkbox" ${s.rules?"checked":""}> <span>I have read the practice test reminders.</span></label><label class="ack"><input id="deskAck" type="checkbox" ${s.desk?"checked":""}> <span>I have cleared my workspace.</span></label><div class="btn-row"><button id="checkinBtn" class="btn" ${s.rules&&s.desk?"":"disabled"}>Continue</button></div></section></main>`}
function room(){return`<main class="page"><section class="card compact"><div class="kicker">Check-in</div><h2>Enter room code</h2><p>Your proctor provides the room code.</p><div class="field"><label for="room">Room code</label><input id="room" class="text-input center mono" maxlength="5" value="${esc(s.roomCode)}" placeholder="AZM24"></div><div class="btn-row"><button id="roomBtn" class="btn">Next</button></div></section></main>`}
function startCode(){return`<main class="page"><section class="card compact center-card"><div class="kicker">Ready to begin</div><h2>Enter start code</h2><p>Your proctor announces the start code.</p><div class="code-row">${Array.from({length:6},(_,i)=>`<input class="code-input start-digit" maxlength="1" inputmode="numeric" data-pos="${i}" aria-label="Start code digit ${i+1}" value="${esc(s.startCode[i]||"")}">`).join("")}</div><div class="btn-row center-row"><button id="startTestBtn" class="btn">Start test</button></div></section></main>`}
function directions(){const x=m(),isMath=x.section==="Math",v=x.id==="rw2"?s.adaptive.rw:x.id==="math2"?s.adaptive.math:null;return`<main class="page"><section class="card"><div class="kicker">${esc(x.section)} · ${esc(x.label)}</div><h2>Directions</h2><p>${isMath?"Calculator use is permitted on every Math question. The calculator and reference sheet are available through Test tools.":"Each question uses a short passage or set of information. Choose the answer that best completes the task."}</p><div class="info-grid"><div class="info-box"><div class="value">${x.minutes}:00</div><div class="label">Module time</div></div><div class="info-box"><div class="value">${x.count}</div><div class="label">Questions</div></div></div>${v?`<div class="notice">Practice routing selected the <b>${esc(v)}</b> difficulty variant.</div>`:""}<ul class="check-list"><li>The timer runs for this module only.</li><li>You can use the question menu before submitting.</li><li>After submission, this module cannot be reopened.</li></ul><div class="btn-row"><button id="beginModuleBtn" class="btn">Begin module</button></div></section></main>`}
function test(){const x=q(),r=rem(),hide=s.timerHidden&&r>C.warnSec;return`<div class="test-shell"><header class="test-top"><div class="test-title">${esc(m().section)} · ${esc(m().label)}</div><div class="test-counter">Question ${s.qi+1} of ${m().count}</div><div id="timer" class="timer ${r<=C.warnSec?"warning":""} ${hide?"hidden":""}" aria-live="polite">${fmt(r)}</div><button id="toolsBtn" class="nav-pill">Test tools</button></header><main class="test-main"><section class="source-panel">${source(x)}</section><section class="question-panel"><div class="question-card"><div class="q-meta">${esc(x.domain||"Question")} · ${esc(x.skill||"")} · ${esc(x.difficulty||"")}</div><h2 id="questionPrompt" class="q-prompt" tabindex="-1">${esc(x.prompt)}</h2>${x.type==="spr"?`<div class="spr-wrap"><label for="spr">Enter your answer</label><input id="spr" class="spr-input mono" inputmode="decimal" value="${esc(s.answers[qkey()]||"")}" placeholder="Answer"></div>`:choices(x)}</div></section></main><footer class="test-footer"><div class="footer-left"><button id="markBtn" class="nav-pill">${marked()?"Unmark":"Mark for review"}</button><button id="reviewBtn" class="nav-pill">Question menu</button>${s.notes[qkey()]?'<span class="annotation-chip">Note saved</span>':""}</div><div class="footer-center"><button id="prevBtn" class="nav-pill" ${s.qi===0?"disabled":""}>Back</button><button id="nextBtn" class="nav-pill primary">${s.qi===m().count-1?"Review module":"Next"}</button></div></footer>${s.lineReader?'<div class="line-reader" aria-hidden="true"></div>':""}</div>`}
function breakPage(){return`<main class="page"><section class="card compact center-card"><div class="kicker">Section break</div><h1>10-minute break</h1><p>Reading and Writing is complete. The break is required before Math begins.</p><div id="breakClock" class="break-clock">${fmt(Math.max(0,Math.ceil((s.breakEndAt-Date.now())/1000)))}</div><p class="small">You cannot advance early.</p></section></main>`}
function finish(){const z=scoreAll();return`<main class="page"><section class="card compact center-card"><div class="kicker">Practice complete</div><h1>Test submitted</h1><p>Responses are saved locally. This practice simulator does not submit results to College Board.</p><div class="info-grid"><div class="info-box"><div class="value">${z.correct}</div><div class="label">Correct</div></div><div class="info-box"><div class="value">${z.answered}</div><div class="label">Answered</div></div><div class="info-box"><div class="value">98</div><div class="label">Questions</div></div><div class="info-box"><div class="value">${z.pct}%</div><div class="label">Accuracy</div></div></div><div class="btn-row center-row"><button id="restartBtn" class="btn">Start another practice test</button></div></section></main>`}
function scoreAll(){let correct=0,answeredN=0;C.mods.forEach(x=>{const a=x.id==="rw2"?B.rw2?.[s.adaptive.rw]||[]:x.id==="math2"?B.math2?.[s.adaptive.math]||[]:B[x.bank]||[];a.forEach((q,i)=>{const v=s.answers[`${x.id}-${i}`];if(v!==undefined&&String(v).trim()!==""){answeredN++;if(String(v).trim().toLowerCase()===String(q.answer).trim().toLowerCase())correct++}})});return{correct,answered:answeredN,pct:Math.round(correct/98*100)}}
function page(){switch(s.screen){case"access":return shell(access());case"checkin":return shell(checkin());case"room":return shell(room());case"startcode":return shell(startCode());case"directions":return shell(directions());case"test":return test();case"break":return shell(breakPage());case"finish":return shell(finish());default:return shell(access())}}
function bind(){if(s.screen==="access"){document.getElementById("access")?.addEventListener("input",e=>{s.accessCode=e.target.value.toUpperCase();save()});document.getElementById("student")?.addEventListener("input",e=>{s.student=e.target.value;save()});document.getElementById("accessBtn")?.addEventListener("click",()=>{if(!C.accessCodes.includes(s.accessCode.trim().toUpperCase()))return toast("Invalid practice access code.");if(!s.student.trim())return toast("Enter a name.");show("checkin")});document.getElementById("resetBtn")?.addEventListener("click",()=>reset())}
if(s.screen==="checkin"){document.getElementById("rulesAck")?.addEventListener("change",e=>{s.rules=e.target.checked;save();render()});document.getElementById("deskAck")?.addEventListener("change",e=>{s.desk=e.target.checked;save();render()});document.getElementById("checkinBtn")?.addEventListener("click",()=>{if(s.rules&&s.desk)show("room")})}
if(s.screen==="room"){document.getElementById("room")?.addEventListener("input",e=>{s.roomCode=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,5);e.target.value=s.roomCode;save()});document.getElementById("roomBtn")?.addEventListener("click",()=>{if(s.roomCode!==C.roomCode)return toast("Invalid room code.");s.startCode="";show("startcode");document.querySelector(".start-digit")?.focus()})}
if(s.screen==="startcode"){const d=[...document.querySelectorAll(".start-digit")];d.forEach((x,i)=>x.addEventListener("input",e=>{x.value=e.target.value.replace(/\D/g,"").slice(-1);s.startCode=d.map(y=>y.value).join("");save();if(x.value&&d[i+1])d[i+1].focus()}));document.getElementById("startTestBtn")?.addEventListener("click",()=>{if(s.startCode!==C.startCode)return toast("Invalid start code.");s.mi=0;s.qi=0;show("directions")})}
if(s.screen==="directions")document.getElementById("beginModuleBtn")?.addEventListener("click",begin);
if(s.screen==="test"){document.querySelectorAll("[data-answer]").forEach(b=>b.addEventListener("click",()=>answer(b.dataset.answer)));document.querySelectorAll("[data-eliminate]").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();eliminate(+b.dataset.eliminate)}));document.getElementById("spr")?.addEventListener("input",e=>spr(e.target.value));document.getElementById("markBtn")?.addEventListener("click",mark);document.getElementById("reviewBtn")?.addEventListener("click",review);document.getElementById("prevBtn")?.addEventListener("click",back);document.getElementById("nextBtn")?.addEventListener("click",next);document.getElementById("toolsBtn")?.addEventListener("click",tools)}
if(s.screen==="finish")document.getElementById("restartBtn")?.addEventListener("click",reset)}
function reset(){stop();try{localStorage.removeItem(C.storageKey)}catch(_){}s=fresh();render()}
document.addEventListener("keydown",e=>{if(s.screen!=="test"||["INPUT","TEXTAREA"].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(k==="f"){mark();e.preventDefault()}else if(k==="m"){review();e.preventDefault()}else if(k==="t"){tools();e.preventDefault()}else if(e.key==="ArrowRight"){next();e.preventDefault()}else if(e.key==="ArrowLeft"){back();e.preventDefault()}else if(e.key==="Escape")closeOverlays()});
window.resetAzamanSAT=reset;render();
})();
