const fs = require('fs');
const assert = require('assert');

const read = (path) => fs.readFileSync(path, 'utf8');
const html = read('index.html');
const app = read('app.js');
const keyboard = read('keyboard.js');
const modal = read('modal-enhancement.js');
const calculator = read('calculator-enhancement.js');
const codeInput = read('code-input-enhancement.js');
const uiA11y = read('ui-accessibility-enhancement.js');

assert(html.includes('<html lang="en">'), 'document language must be declared');
assert(app.includes('aria-live'), 'application status region must expose live updates');
assert(app.includes('aria-label="Answer choices"'), 'answer-choice group must be labelled');
assert(app.includes('aria-pressed'), 'selected choices must expose pressed state');
assert(app.includes('aria-labelledby="warnTitle"'), 'timer warning must have an accessible name');
assert(keyboard.includes('role="dialog"'), 'shortcut dialog must expose dialog role');
assert(keyboard.includes('openHelp'), 'help shortcut must have a dedicated help dialog');
assert(keyboard.includes('Ctrl + Alt + H'), 'Windows/ChromeOS help shortcut must be exposed');
assert(keyboard.includes('Command + Control + H'), 'macOS help shortcut must be exposed');
assert(keyboard.includes('Command + Control + P'), 'iPad help shortcut must be exposed');
assert(keyboard.includes('Command + Shift + V'), 'macOS Mark for Review shortcut must be exposed');
assert(keyboard.includes('Command + Option + T'), 'macOS timer shortcut must be exposed');
assert(keyboard.includes('const isMac'), 'platform-specific shortcut routing must detect Apple platforms');
assert(keyboard.includes('const isIPad'), 'iPad-specific shortcut routing must be supported');
assert(modal.includes('role="dialog"'), 'modal focus layer must target dialog semantics');
assert(modal.includes('aria-modal="true"'), 'dialogs must be modal to assistive technology');
assert(modal.includes('FOCUSABLE'), 'dialogs must define keyboard focusable controls');
assert(calculator.includes('aria-controls="azmCalcCalculate"'), 'calculator tabs must expose tabpanel relationship');
assert(calculator.includes('aria-controls="azmCalcGraph"'), 'graph tab must expose tabpanel relationship');
assert(calculator.includes('aria-selected'), 'calculator tabs must expose selection state');
assert(codeInput.includes('setAttribute(\'aria-label\''), 'start-code fields must receive individual accessible labels');
assert(codeInput.includes('Start code digit ${index + 1} of 6'), 'start-code labels must identify each digit position');
assert(uiA11y.includes("setAttribute('role', 'radio')"), 'answer choices must expose radio semantics');
assert(uiA11y.includes("setAttribute('aria-checked'"), 'answer choices must expose checked state');
assert(uiA11y.includes("setAttribute('role', 'menu')"), 'test tools must expose menu semantics');
assert(uiA11y.includes('Question ${number}, ${states.join'), 'review buttons must have descriptive labels');
assert(html.includes('ui-accessibility-enhancement.js'), 'semantic accessibility enhancement must be loaded');

console.log('Accessibility contract checks passed.');
